# Author - Eva Sinha, Stanford University, esinha@stanford.edu
# Date   - 13th July, 2017
#
color_pal = c( 'Historical'                                         = 'black',
               'SSP1 (Sustainability)'                              ='#00FF00',
               'SSP4 (Inequality (3.4))'                            ='#FFFF00',
               'SSP2 (Middle of the road)'                          ='#0000FF',
               'SSP4 (Inequality (6.0))'                            ='#FFA500',
               'SSP3 (Regional rivalry)'                            ='#FF0000',
               'SSP5 (Fossil-fueled)'                               ='#A020F0',
               'Government of India Directorate of Economics and Statistics' = 'darkred',
               'Government of India'                                = 'darkred',
               'LUH2'                                               = 'black',
               'India E and S'                                      = 'darkred',
               
               'Indus'                                              = '#f1fcb3',
               'Indus (Up to border) Basin'                         = '#f1fcb3',
               'Barak'                                              = '#fcebd7',
               'Barak and others Basin'                             = '#fcebd7',
               'Brahmani_Baitarni'                                  = 'blue',   # '#fce7c0',
               'Brahmani and Baitarni'                              = 'blue',   # '#fce7c0',
               'Brahmani and Baitarni Basin'                        = 'blue',   # '#fce7c0',
               'Brahmaputra'                                        = '#b6d4fc',
               'Brahmaputra Basin'                                  = '#b6d4fc',
               'Cauvery'                                            = '#addd8e',   # '#fcd4d5',
               'Cauvery Basin'                                      = '#addd8e',   # '#fcd4d5',
               'East_Mahanadi_Pennar'                               = '#ccfcd5',
               'East flowing rivers between Mahanadi and Pennar'    = '#ccfcd5',
               'East flowing rivers between Pennar and Kanyakumari' = '#b6f4fc',
               'East_Pennar_Kanyakumari'                            = '#b6f4fc',
               'Ganga Basin'                                        = 'deepskyblue', # '#bde5fc',
               'Ganga (within India)'                               = 'deepskyblue', # '#bde5fc',
               'Ganga Basin (within India)'                         = 'deepskyblue', # '#bde5fc',
               'Godavari'                                           = '#41ab5d',   # '#cdb3fc',
               'Godavari Basin'                                     = '#41ab5d',   # '#cdb3fc',
               'Krishna'                                            = '#fe9929',   # '#b8fcc1',
               'Krishna Basin'                                      = '#fe9929',   # '#b8fcc1',
               'Mahanadi'                                           = '#005a32',   # '#d1fcb3',
               'Mahanadi Basin'                                     = '#005a32',   # '#d1fcb3',
               'Mahi'                                               = '#A020F0',   # '#fccffc',
               'Mahi Basin'                                         = '#A020F0',   # '#fccffc',
               'Minor_Myanmar_Bangladesh'                           = '#f4fcc7',
               'Minor rivers draining into Myanmar and Bangladesh'  = '#f4fcc7',
               'Narmada'                                            = 'cyan2',    # '#f6b3fc',
               'Narmada Basin'                                      = 'cyan2',    # '#f6b3fc',
               'Pennar'                                             = '#e7fcd7',
               'Pennar Basin'                                       = '#e7fcd7',
               'Sabarmati'                                          = '#fcb3df',
               'Sabarmati Basin'                                    = '#fcb3df',
               'Subernarekha'                                       = 'mediumpurple1',   # '#fcd7ed',
               'Subernarekha Basin'                                 = 'mediumpurple1',   # '#fcd7ed',
               'Tapi'                                               = 'darkred',         # '#bbfce4',
               'Tapi Basin'                                         = 'darkred',         # '#bbfce4',
               'West_Kutch_Saurashtra'                              = '#d7fcf1',
               'West flowing rivers of Kutch & Saurashtra in. Luni' = '#d7fcf1',
               'West_Tadri_Kanyakumari'                             = '#d4d9fc',
               'West flowing rivers from Tadri to Kanyakumari'      = '#d4d9fc',
               'West_Tapi_Tadri'                                    = '#c5c7fc',
               'West flowing rivers from Tapi to Tadri'             = '#c5c7fc',
               
               'Jenapur'                                            = 'blue',            # '#00FF00',
               'Musiri'                                             = '#FFFF00',
               'Polavaram'                                          = '#41ab5d',         # '#0000FF',
               'Vijayawada'                                         = '#fe9929',         # '#FFA500',
               'Tikarapara'                                         = '#005a32',         # '#FF0000',
               'Ghatsila'                                           = 'mediumpurple1',   # 'magenta',
               'Mandleshwar'                                        = 'cyan2',           # 'darkgreen',
               'Urachikottai'                                       = '#addd8e',         # 'brown',
               'All basins'                                         = 'black',
               'All India average'                                  = 'black',
               
               'fert_kgN_ha'                                        = 'darkred',
               'fert_kgN_km2'                                       = 'darkred',
               'precip'                                             = 'deepskyblue',
               'precip_JJAS'                                        = 'blue',
               'precip_JAS'                                         = 'purple',
               'precip_JASO'                                        = 'purple',
               'precip_ASO'                                         = 'deepskyblue',
               
               'temp'                                               = 'burlywood',
               'temp_JJAS'                                          = 'goldenrod',
               'temp_JAS'                                           = 'goldenrod',
               'temp_JASO'                                          = 'goldenrod',
               'temp_ASO'                                           = 'goldenrod',
               
               'italic(Q)[DIN]~(kg~N~km^-2~month^-1)'                     = 'red',
               'italic(Q)~(mm~month^-1)'                            = 'blue',
               'italic(P)~(mm~month^-1)'                             = 'green',
               
               'Discharge~(m^3/sec)'                                = 'lightsteelblue1',
               'Discharge~(mm/yr)'                                  = 'lightsteelblue1',
               'Discharge_m3s'                                      = 'lightsteelblue1',
               'Disch_mm_yr'                                        = 'lightsteelblue1',
               'Discharge_m3s_JJAS'                                 = 'royalblue1',
               'Disch_mm_yr_JJAS'                                   = 'royalblue1',
               'Discharge~JJAS~(mm/yr)'                             = 'royalblue1',
               'WRTDS~estimated~DIN~flux'                           = 'red',
               'WRTDS_DIN_flux'                                     = 'red',
               'WRTDS~estimated~annual~DIN~flux'                    = 'red',
               
               'CPC~CRU~data'                                       = 'cyan',
               'CPC~CRU~data~with~LSC~timeseries'                   = 'blue',
               'IMD~data'                                           = 'green',
               'IMD~data~with~LSC~timeseries'                       = 'darkgreen',
               
               'Predicted~DIN~flux'                                 = 'black',
               'Predicted~DIN~flux~(all~basin~model)'               = 'deepskyblue',
               'ln_DIN_flux'                                        = 'red',
               
               'pre_gt_10'                                          = 'cyan',
               'pre_gt_20'                                          = 'cyan',
               'pre_gt_10_JJAS'                                     = 'cyan',
               'pre_gt_20_JJAS'                                     = 'cyan',
               'pre_gt_10_JAS'                                      = 'cyan',
               'pre_gt_20_JAS'                                      = 'cyan',
               'pre_gt_10_JASO'                                     = 'cyan',
               'pre_gt_20_JASO'                                     = 'cyan',
               'pre_gt_10_ASO'                                      = 'cyan',
               'pre_gt_20_ASO'                                      = 'cyan',
               
               'R90pTOT'                                            = 'dodgerblue',
               'R95pTOT'                                            = 'cyan',
               'R99pTOT'                                            = 'cyan',
               
               'R90pTOT_JJAS_1'                                     = 'cyan',
               'R95pTOT_JJAS_1'                                     = 'cyan',
               'R99pTOT_JJAS_1'                                     = 'cyan',
               'R90pTOT_JAS_1'                                      = 'cyan',
               'R95pTOT_JAS_1'                                      = 'cyan',
               'R99pTOT_JAS_1'                                      = 'cyan4',
               'R90pTOT_JASO_1'                                     = 'cyan',
               'R95pTOT_JASO_1'                                     = 'cyan',
               'R99pTOT_JASO_1'                                     = 'cyan',
               'R90pTOT_ASO_1'                                      = 'cyan',
               'R95pTOT_ASO_1'                                      = 'cyan',
               'R99pTOT_ASO_1'                                      = 'cyan',
               
               'R90pTOT_JJAS_2'                                     = 'cyan',
               'R95pTOT_JJAS_2'                                     = 'cyan',
               'R99pTOT_JJAS_2'                                     = 'cyan',
               'R90pTOT_JAS_2'                                      = 'cyan',
               'R95pTOT_JAS_2'                                      = 'cyan',
               'R99pTOT_JAS_2'                                      = 'cyan',
               'R90pTOT_JASO_2'                                     = 'cyan',
               'R95pTOT_JASO_2'                                     = 'cyan',
               'R99pTOT_JASO_2'                                     = 'cyan',
               'R90pTOT_ASO_2'                                      = 'cyan',
               'R95pTOT_ASO_2'                                      = 'cyan',
               'R99pTOT_ASO_2'                                      = 'cyan',
               
               'Year'                                               = 'black',
               'italic(N)[Dep]'                                     = 'yellow', # 'italic(ND)'
               'ln(italic(N)[Dep])'                                 = 'yellow',  # 'italic(f)[ND]'
               'italic(N)[Fert]'                                    = 'darkred', # 'italic(FU)'
               'ln(italic(N)[Fert])'                                = 'darkred', # 'italic(f)[FU]'
               'italic(N)[Fert~`,`~Dep]'                                = 'darkred', # 'italic(FU~ND)'
               'ln(italic(N)[Fert~`,`~Dep])'                            = 'darkred', # 'italic(f)[FU~ND]'
               'italic(GSC)'                                        = 'black',
               'italic(LSC)~(MCM)'                                  = 'black',
               'italic(LSC)~(MCM~mm^-1)'                            = 'black',
               'italic(LSC)'                                        = 'black',
               'Intercept'                                          = 'gray75',
               'italic(P)[Annual]'                                  = 'blue4',
               'italic(P)[JJAS]'                                    = 'dodgerblue',
               'italic(P)[JAS]'                                     = 'dodgerblue',
               'italic(P)[JASO]'                                    = 'dodgerblue',
               'italic(P)[ASO]'                                     = 'dodgerblue',
               
               'italic(n)[P>10~mm]'                                 = 'blueviolet',
               'italic(n)[P>20~mm]'                                 = 'blueviolet',
               'italic(n)[JJAS~P>10~mm]'                            = 'blueviolet',
               'italic(n)[JJAS~P>20~mm]'                            = 'blueviolet',
               'italic(n)[JAS~P>10~mm]'                             = 'blueviolet',
               'italic(n)[JAS~P>20~mm]'                             = 'blueviolet',
               'italic(n)[JASO~P>10~mm]'                            = 'blueviolet',
               'italic(n)[JASO~P>20~mm]'                            = 'blueviolet',
               'italic(n)[ASO~P>10~mm]'                             = 'blueviolet',
               'italic(n)[ASO~P>20~mm]'                             = 'blueviolet',
               
               'italic(P)[italic(p)>0.90]'                          = 'lightblue',
               'italic(P)[italic(p)>0.95]'                          = 'lightblue',
               'italic(P)[italic(p)>0.99]'                          = 'lightblue',
               
               'italic(P)[JJAS~italic(p)>0.90]'                     = 'cyan',
               'italic(P)[JJAS~italic(p)>0.95]'                     = 'cyan',
               'italic(P)[JJAS~italic(p)>0.99]'                     = 'cyan',
               'italic(P)[JAS~italic(p)>0.90]'                      = 'cyan',
               'italic(P)[JAS~italic(p)>0.95]'                      = 'cyan',
               'italic(P)[JAS~italic(p)>0.99]'                      = 'cyan',
               'italic(P)[JASO~italic(p)>0.90]'                     = 'cyan',
               'italic(P)[JASO~italic(p)>0.95]'                     = 'cyan',
               'italic(P)[JASO~italic(p)>0.99]'                     = 'cyan',
               'italic(P)[ASO~italic(p)>0.90]'                      = 'cyan',
               'italic(P)[ASO~italic(p)>0.95]'                      = 'cyan',
               'italic(P)[ASO~italic(p)>0.99]'                      = 'cyan',
               
               'italic(P)[JJAS~italic(p)(JJAS)>0.90]'               = 'cyan',
               'italic(P)[JJAS~italic(p)(JJAS)>0.95]'               = 'cyan',
               'italic(P)[JJAS~italic(p)(JJAS)>0.99]'               = 'cyan',
               'italic(P)[JAS~italic(p)(JAS)>0.90]'                 = 'cyan',
               'italic(P)[JAS~italic(p)(JAS)>0.95]'                 = 'cyan',
               'italic(P)[JAS~italic(p)(JAS)>0.99]'                 = 'cyan',
               'italic(P)[JASO~italic(p)(JASO)>0.90]'               = 'cyan',
               'italic(P)[JASO~italic(p)(JASO)>0.95]'               = 'cyan',
               'italic(P)[JASO~italic(p)(JASO)>0.99]'               = 'cyan',
               'italic(P)[ASO~italic(p)(ASO)>0.90]'                 = 'cyan',
               'italic(P)[ASO~italic(p)(ASO)>0.95]'                 = 'cyan',
               'italic(P)[ASO~italic(p)(ASO)>0.99]'                 = 'cyan',
               
               'italic(T)[Annual]'                                  = 'burlywood',
               'italic(T)[JJAS]'                                    = 'goldenrod',
               'italic(T)[JAS]'                                     = 'goldenrod',
               'italic(T)[JASO]'                                    = 'goldenrod',
               'italic(T)[ASO]'                                     = 'goldenrod',
               
               'italic(LU)[Urban]'                                  = 'red',
               'italic(LU)[Agriculture]'                            = '#ffd27f',
               'italic(LU)[Forest]'                                 = 'darkgreen',
               'italic(LU)[Shrub]'                                  = '#c43500',
               'italic(LU)[Grass]'                                  = '#e28a64',
               'italic(LU)[Barren]'                                 = '#dec39d')